# Computer vision - Week_00 - numpy recap

NumPy stands for Numerical Python. It is a Python library that provides support for large, multi-dimensional arrays and matrices, along with a range of mathematical functions to operate on these arrays.

NumPy is widely used in scientific computing, data analysis, and machine learning. It provides efficient storage and manipulation of large arrays of numerical data, making it easier to work with data in a variety of formats.

# Python common data structures

In [2]:
my_list = [5,2345,8]
my_list

[5, 2345, 8]

In [37]:
type(my_list)

list

In [50]:
len(my_list)

3

In [40]:
new_set = set(my_list)
new_set

{3, 4, 5, 6, 7, 8}

In [68]:
data = {"my_value" : 35,
 "my_age": 2345,
 "my_school": 324536}

your_data = {"my_value" : 35,
        "my_age": 234546,
        "my_school": 'TULE'}

In [69]:
database = [data, data.copy() ,data.copy(), your_data]

In [71]:
database[0]["my_age"] = 999999

In [72]:
database

[{'my_value': 35, 'my_age': 999999, 'my_school': 324536},
 {'my_value': 35, 'my_age': 2345, 'my_school': 324536},
 {'my_value': 35, 'my_age': 2345, 'my_school': 324536},
 {'my_value': 35, 'my_age': 234546, 'my_school': 'TULE'}]

# 1. Numpy and matrix operation

## INFO: Math entities
Scalars, vectors, matrices, and multidimensional matrices are all mathematical objects that are used in different fields, including linear algebra, physics, and computer science.

**A scalar** is a single number, such as 1, 2.5, or -3. It has no direction or orientation and can be represented by a single value.

**A vector** is an array of numbers arranged in a specific order. It has magnitude (length) and direction and can be represented graphically as an arrow. In two dimensions, a vector can be represented by a pair of numbers (x, y), while in three dimensions, it can be represented by a triplet of numbers (x, y, z).

**A matrix** is a rectangular array of numbers arranged in rows and columns. It can be represented by a two-dimensional array, where each element of the array represents a single value in the matrix.

**A multidimensional matrix** is a matrix with more than two dimensions. It can be represented as an array of arrays, where each element in the array is itself an array representing a lower-dimensional matrix.

In [3]:
import numpy as np
import math

## 1.1 Creation of matrix (manual)

In [4]:
[]

[]

Create empty empty matrix

In [5]:
v_empty = np.array([])
v_empty

array([], dtype=float64)

Row vector / Riadkovy vektor / 1D:  [1 2 3 4]

In [6]:
v_row = np.array([1, 2, 3, 4])
# v_row = np.array([[1], [2], [3], [4]])
v_row.shape

(4,)

Matrix (2D): Manualy defined matrix with two row (1D) vectors [1,2] and [3,4]

In [7]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

Column vector (manually) defined):

In [8]:
np.array([[1], [2], [3], [4]])

array([[1],
       [2],
       [3],
       [4]])

Column vector get by Transpose row vector

In [9]:
v_column = np.array([[1, 2, 3, 4]]).T
v_column

array([[1],
       [2],
       [3],
       [4]])

## 1.2 Spacial initialization of matrix

Linspace:
Oparation linspace return 10 elements from 0 to 9 (linearly spread)

In [10]:
lin_spaced_vector = np.linspace(-5, 2,15)
print(lin_spaced_vector)

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2. ]


Create matrix of zeros (2D)

In [11]:
mat_zeros = np.zeros((3, 3))  # tuple as input param
mat_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Create matrix of zeros (3D)

In [12]:
mat_zeros = np.zeros((3, 3, 3))  # tuple as input param
mat_zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Create matrix of ones with defined resolution

In [13]:
mat_ones = np.ones((3, 2))
mat_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Create diagonal matrix of ones with defined resolution

In [14]:
mat_eye = np.eye(6)
mat_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
((mat_eye * (-1) + 1) * 5) + mat_eye * 8

array([[8., 5., 5., 5., 5., 5.],
       [5., 8., 5., 5., 5., 5.],
       [5., 5., 8., 5., 5., 5.],
       [5., 5., 5., 8., 5., 5.],
       [5., 5., 5., 5., 8., 5.],
       [5., 5., 5., 5., 5., 8.]])

Random initialized values in matrix with define resolution

In [16]:
mat_rand = np.random.rand(2, 3)
mat_rand

array([[0.68110863, 0.46179406, 0.99071253],
       [0.10598444, 0.92903185, 0.18490426]])

## 1.3 Spacial operations

If we wanna diagonal matrix with specific value

In [17]:
mat_eye = np.eye(3)*5
mat_eye

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [18]:
mat_eye

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [19]:
mat_eye==0

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

If we wanna also changes zeros

In [20]:
mat_eye[mat_eye==0] = 3
mat_eye



mat_eye[mat_eye <= 1 ] = -999
mat_eye

array([[5., 3., 3.],
       [3., 5., 3.],
       [3., 3., 5.]])

## 1.4 Get element from matrix

In [21]:
vec = np.array([4, 5, 4, 0, 9])
print(vec[0], type(vec[0]))
print(vec[2], type(vec[2]))
print(vec[0:1], type(vec[0:1]))
print(vec[0:2], type(vec[0:2]))
print(vec[0:3], type(vec[0:3]))
print(vec[3:], type(vec[1:]))
print(vec[:3], type(vec[:3]))
print(vec[-1], type(vec[-1]))
print(vec[0:4], type(vec[0:3]))

4 <class 'numpy.int64'>
4 <class 'numpy.int64'>
[4] <class 'numpy.ndarray'>
[4 5] <class 'numpy.ndarray'>
[4 5 4] <class 'numpy.ndarray'>
[0 9] <class 'numpy.ndarray'>
[4 5 4] <class 'numpy.ndarray'>
9 <class 'numpy.int64'>
[4 5 4 0] <class 'numpy.ndarray'>


In [22]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(mat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
print(mat[1:3])

[[4 5 6]
 [7 8 9]]


In [24]:
# todo -> make clear example
#print("Accessing  element at (2,3) / Pristup k elementu (2,3)", mat[1][2])
#print("Accesing different elements through sequences:/ Dynamicky pristup k elementom matic")
#print(mat[0][:])  # vrati prvy riadok ako riadkovy vektor
#print("")
#print(mat[:][1])  # vrati druhy stlpec ako riadkovy vektor !!!
#print("")
#print(mat[1:3, 1:3])  # submatica zacinajuca na 2,2
#print("")
#print(mat[1:, 1:])  # (2,2) + till end
#print("")
#print(mat[:3, :3])  # od [] -> to index [3 3]

Get resolution/shape of matrix

In [25]:
print("Shape of the matrix/ Rozmery matice: ", mat.shape)
print("Shape of the matrix/ Rozmery matice: ", mat.shape[0])
print("Shape of the matrix/ Rozmery matice: ", mat.shape[1])

Shape of the matrix/ Rozmery matice:  (4, 3)
Shape of the matrix/ Rozmery matice:  4
Shape of the matrix/ Rozmery matice:  3


In [26]:
# Jednoduché operácie s vektormi a maticam:

## 1.5 Matrix and math operations

In [27]:
vec_a = np.array([[1, 2, 3, 4]]).T
print(vec_a)

[[1]
 [2]
 [3]
 [4]]


In [28]:
vec_b = np.array([[2, 4, 6, 8]])
print(vec_b)

[[2 4 6 8]]


In [29]:
# WARNING
test_v = np.array([1, 2, 3, 4])
print(test_v)
print(test_v.T)

[1 2 3 4]
[1 2 3 4]


In [30]:
test_v = np.array([[1, 2, 3, 4]])
print(test_v)
print(test_v.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [31]:
print(2 * vec_a)

[[2]
 [4]
 [6]
 [8]]


In [32]:
print(vec_a / 2)

[[0.5]
 [1. ]
 [1.5]
 [2. ]]


In [33]:
print(vec_a ** 3)

[[ 1]
 [ 8]
 [27]
 [64]]


In [34]:
print(vec_a * vec_b)

[[ 2  4  6  8]
 [ 4  8 12 16]
 [ 6 12 18 24]
 [ 8 16 24 32]]


In [35]:
print(vec_a * (vec_a+2))

[[ 3]
 [ 8]
 [15]
 [24]]


In [36]:
print(vec_a / vec_a)

[[1.]
 [1.]
 [1.]
 [1.]]


In [37]:
print(vec_b / vec_a)

[[2.         4.         6.         8.        ]
 [1.         2.         3.         4.        ]
 [0.66666667 1.33333333 2.         2.66666667]
 [0.5        1.         1.5        2.        ]]


In [38]:
print(vec_a - vec_b)

[[-1 -3 -5 -7]
 [ 0 -2 -4 -6]
 [ 1 -1 -3 -5]
 [ 2  0 -2 -4]]


In [39]:
print(vec_b - vec_a)

[[ 1  3  5  7]
 [ 0  2  4  6]
 [-1  1  3  5]
 [-2  0  2  4]]


In [40]:
print(np.log(vec_a))

[[0.        ]
 [0.69314718]
 [1.09861229]
 [1.38629436]]


In [41]:
print(np.round(np.log(vec_a),2))

[[0.  ]
 [0.69]
 [1.1 ]
 [1.39]]


 ## 1.6 Matrix scalar operations

In [42]:
print(np.sum(vec_a)) # sucet
print(np.mean(vec_a)) # priemer
print(np.var(vec_a)) # rozptil
print(np.std(vec_a)) # smerodajna odchylka
print(np.min(vec_a), np.max(vec_a)) #min, max

10
2.5
1.25
1.118033988749895
1 4


In [43]:
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
print("Max of mat along axis 0: ", np.max(mat, 0))
print("Max of mat along axis 1: ", np.max(mat, 1))
print("Mean of mat along axis 0: ", np.mean(mat, 0))
print("Mean of mat along axis 1: ", np.mean(mat, 1))

Max of mat along axis 0:  [10 11 12]
Max of mat along axis 1:  [ 3  6  9 12]
Mean of mat along axis 0:  [5.5 6.5 7.5]
Mean of mat along axis 1:  [ 2.  5.  8. 11.]


Determinant

In [45]:
matrix = np.random.rand(4,4)
matrix
# np.linalg.det(matrix)

array([[0.07125326, 0.8223147 , 0.86224915, 0.63107807],
       [0.76789702, 0.08750262, 0.63730842, 0.57829087],
       [0.7567088 , 0.94919419, 0.0164672 , 0.74755695],
       [0.21945033, 0.5535335 , 0.25893179, 0.52119733]])

Get diagonal from matrix

In [46]:
print(np.diag(matrix))

[0.07125326 0.08750262 0.0164672  0.52119733]


In [47]:
print(np.diag(matrix,2))

[0.86224915 0.57829087]


In [48]:
print(np.diag(matrix,-1))

[0.76789702 0.94919419 0.25893179]


In [49]:
A

array([[1, 2],
       [3, 4]])

In [50]:
print(np.repeat(A, 2,axis=0))

[[1 2]
 [1 2]
 [3 4]
 [3 4]]


In [51]:
np.repeat(A, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [52]:
print(np.repeat(A, 2,axis=1))

[[1 1 2 2]
 [3 3 4 4]]


In [53]:
A

array([[1, 2],
       [3, 4]])

In [54]:
np.append(A, A*(-1),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [55]:
np.append(A, A*(-1),axis=1)

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [56]:
matrix

array([[0.07125326, 0.8223147 , 0.86224915, 0.63107807],
       [0.76789702, 0.08750262, 0.63730842, 0.57829087],
       [0.7567088 , 0.94919419, 0.0164672 , 0.74755695],
       [0.21945033, 0.5535335 , 0.25893179, 0.52119733]])

Change shape of matrix

In [57]:
matrix.reshape(2,8)

array([[0.07125326, 0.8223147 , 0.86224915, 0.63107807, 0.76789702,
        0.08750262, 0.63730842, 0.57829087],
       [0.7567088 , 0.94919419, 0.0164672 , 0.74755695, 0.21945033,
        0.5535335 , 0.25893179, 0.52119733]])

Matrix concatenation

In [58]:
np.concatenate((vec_a, vec_b.T), 0)

array([[1],
       [2],
       [3],
       [4],
       [2],
       [4],
       [6],
       [8]])

In [59]:
np.concatenate((vec_a, vec_b.T), 1)

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [60]:
np.array((vec_a, vec_b))

/var/folders/mt/zbsgqls91d5c1dt725ckq4lc0000gn/T/ipykernel_74652/2904819320.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array((vec_a, vec_b))


array([array([[1],
              [2],
              [3],
              [4]]), array([[2, 4, 6, 8]])], dtype=object)

 ## 1.7 Matrix vector operations

Velmi dolezitymi operaciami s maticami su vypocty skalarnych a vektorovych sucinov. Tieto operacie si je potrebne osvojit a vediet sa orientovat v roznych zapisoch.

In [61]:
mat_a = np.array([[1, 2, 3]])
mat_b = np.array([[4, 5, 6]])

In [62]:
print(mat_a * mat_b)    # elementwise
print(mat_a.T * mat_b)  # vektorovy sucin
print(mat_a * mat_b.T)  # vektorovy sucin
print(mat_a.T @ mat_b)  # skalarny sucin

[[ 4 10 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


# Linear algebra:

In [63]:
V, D = np.linalg.eig(np.random.rand(3, 3))
print("Eigen values: \n",V,"\n Eigen matrix\n",D)

Eigen values: 
 [-0.44179474  0.5796728   1.20401036] 
 Eigen matrix
 [[ 0.63410244 -0.23090099 -0.37695771]
 [ 0.2368094   0.88367457 -0.73337265]
 [-0.7360947  -0.40719037 -0.56574503]]


In [64]:
U, S, V = np.linalg.svd(np.random.rand(3, 3))
print("SVD single value decomposition: \n", U,"\n Eigen matrix\n",S,"\n Eigen matrix\n",V) # a = U * S * V'

SVD single value decomposition: 
 [[-0.57515584  0.55055595 -0.60504868]
 [-0.4288109  -0.8327767  -0.3501488 ]
 [-0.69664695  0.05806134  0.71506077]] 
 Eigen matrix
 [2.04013375 0.36072223 0.25172336] 
 Eigen matrix
 [[-0.63365218 -0.48734951 -0.60081226]
 [-0.59580925  0.80280177 -0.02281781]
 [ 0.4934534   0.34351095 -0.79906444]]
