In [49]:
my_list = [5,2345,8]
my_list

[5, 6, 8]

In [37]:
type(my_list)

list

In [50]:
len(my_list)

3

In [40]:
new_set = set(my_list)
new_set

{3, 4, 5, 6, 7, 8}

In [68]:
data = {"my_value" : 35,
 "my_age": 2345,
 "my_school": 324536}

your_data = {"my_value" : 35,
        "my_age": 234546,
        "my_school": 'TULE'}

In [69]:
database = [data, data.copy() ,data.copy(), your_data]

In [71]:
database[0]["my_age"] = 999999

In [72]:
database

[{'my_value': 35, 'my_age': 999999, 'my_school': 324536},
 {'my_value': 35, 'my_age': 2345, 'my_school': 324536},
 {'my_value': 35, 'my_age': 2345, 'my_school': 324536},
 {'my_value': 35, 'my_age': 234546, 'my_school': 'TULE'}]

# 1. Numpy and matrix operation

In [74]:
import numpy as np
import math

## 1.1 Creation of matrix (manual)

In [75]:
[]

[]

Create empty empty matrix

In [80]:
v_empty = np.array([])
v_empty

array([], dtype=float64)

Row vector / Riadkovy vektor / 1D:  [1 2 3 4]

In [89]:
v_row = np.array([1, 2, 3, 4])
# v_row = np.array([[1], [2], [3], [4]])
v_row.shape

(4,)

Matrix (2D): Manualy defined matrix with two row (1D) vectors [1,2] and [3,4]

In [90]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

Column vector (manually) defined):

In [91]:
np.array([[1], [2], [3], [4]])

array([[1],
       [2],
       [3],
       [4]])

Column vector get by Transpose row vector

In [93]:
v_column = np.array([[1, 2, 3, 4]]).T
v_column

array([[1],
       [2],
       [3],
       [4]])

## 1.2 Spacial initialization of matrix

Linspace:
Oparation linspace return 10 elements from 0 to 9 (linearly spread)

In [73]:
lin_spaced_vector = np.linspace(-5, 2,15)
print(lin_spaced_vector)

[-5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5
  2. ]


Create matrix of zeros (2D)

In [74]:
mat_zeros = np.zeros((3, 3))  # tuple as input param
mat_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Create matrix of zeros (3D)

In [75]:
mat_zeros = np.zeros((3, 3, 3))  # tuple as input param
mat_zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

Create matrix of ones with defined resolution

In [76]:
mat_ones = np.ones((3, 2))
mat_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Create diagonal matrix of ones with defined resolution

In [77]:
mat_eye = np.eye(6)
mat_eye

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [78]:
((mat_eye * (-1) + 1) * 5) + mat_eye * 8

array([[8., 5., 5., 5., 5., 5.],
       [5., 8., 5., 5., 5., 5.],
       [5., 5., 8., 5., 5., 5.],
       [5., 5., 5., 8., 5., 5.],
       [5., 5., 5., 5., 8., 5.],
       [5., 5., 5., 5., 5., 8.]])

Random initialized values in matrix with define resolution

In [79]:
mat_rand = np.random.rand(2, 3)
mat_rand

array([[0.25651032, 0.50701782, 0.94378995],
       [0.52751129, 0.87494777, 0.03541119]])

## 1.3 Spacial operations

If we wanna diagonal matrix with specific value

In [80]:
mat_eye = np.eye(3)*5
mat_eye

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [81]:
mat_eye

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [82]:
mat_eye==0

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

If we wanna also changes zeros

In [83]:
mat_eye[mat_eye==0] = 3
mat_eye



mat_eye[mat_eye <= 1 ] = -999
mat_eye

array([[5., 3., 3.],
       [3., 5., 3.],
       [3., 3., 5.]])

## 1.4 Get element from matrix

In [84]:
vec = np.array([4, 5, 4, 0, 9])
print(vec[0], type(vec[0]))
print(vec[2], type(vec[2]))
print(vec[0:1], type(vec[0:1]))
print(vec[0:2], type(vec[0:2]))
print(vec[0:3], type(vec[0:3]))
print(vec[3:], type(vec[1:]))
print(vec[:3], type(vec[:3]))
print(vec[-1], type(vec[-1]))
print(vec[0:4], type(vec[0:3]))

4 <class 'numpy.int64'>
4 <class 'numpy.int64'>
[4] <class 'numpy.ndarray'>
[4 5] <class 'numpy.ndarray'>
[4 5 4] <class 'numpy.ndarray'>
[0 9] <class 'numpy.ndarray'>
[4 5 4] <class 'numpy.ndarray'>
9 <class 'numpy.int64'>
[4 5 4 0] <class 'numpy.ndarray'>


In [85]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(mat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [86]:
print(mat[1:3])

[[4 5 6]
 [7 8 9]]


In [87]:
# todo -> make clear example
#print("Accessing  element at (2,3) / Pristup k elementu (2,3)", mat[1][2])
#print("Accesing different elements through sequences:/ Dynamicky pristup k elementom matic")
#print(mat[0][:])  # vrati prvy riadok ako riadkovy vektor
#print("")
#print(mat[:][1])  # vrati druhy stlpec ako riadkovy vektor !!!
#print("")
#print(mat[1:3, 1:3])  # submatica zacinajuca na 2,2
#print("")
#print(mat[1:, 1:])  # (2,2) + till end
#print("")
#print(mat[:3, :3])  # od [] -> to index [3 3]

Get resolution/shape of matrix

In [88]:
print("Shape of the matrix/ Rozmery matice: ", mat.shape)
print("Shape of the matrix/ Rozmery matice: ", mat.shape[0])
print("Shape of the matrix/ Rozmery matice: ", mat.shape[1])

Shape of the matrix/ Rozmery matice:  (4, 3)
Shape of the matrix/ Rozmery matice:  4
Shape of the matrix/ Rozmery matice:  3


In [89]:
# Jednoduché operácie s vektormi a maticam:

## 1.5 Matrix and math operations

In [90]:
vec_a = np.array([[1, 2, 3, 4]]).T
print(vec_a)

[[1]
 [2]
 [3]
 [4]]


In [91]:
vec_b = np.array([[2, 4, 6, 8]])
print(vec_b)

[[2 4 6 8]]


In [92]:
# WARNING
test_v = np.array([1, 2, 3, 4])
print(test_v)
print(test_v.T)

[1 2 3 4]
[1 2 3 4]


In [93]:
test_v = np.array([[1, 2, 3, 4]])
print(test_v)
print(test_v.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [94]:
print(2 * vec_a)

[[2]
 [4]
 [6]
 [8]]


In [95]:
print(vec_a / 2)

[[0.5]
 [1. ]
 [1.5]
 [2. ]]


In [96]:
print(vec_a ** 3)

[[ 1]
 [ 8]
 [27]
 [64]]


In [97]:
print(vec_a * vec_b)

[[ 2  4  6  8]
 [ 4  8 12 16]
 [ 6 12 18 24]
 [ 8 16 24 32]]


In [98]:
print(vec_a * (vec_a+2))

[[ 3]
 [ 8]
 [15]
 [24]]


In [99]:
print(vec_a / vec_a)

[[1.]
 [1.]
 [1.]
 [1.]]


In [100]:
print(vec_b / vec_a)

[[2.         4.         6.         8.        ]
 [1.         2.         3.         4.        ]
 [0.66666667 1.33333333 2.         2.66666667]
 [0.5        1.         1.5        2.        ]]


In [101]:
print(vec_a - vec_b)

[[-1 -3 -5 -7]
 [ 0 -2 -4 -6]
 [ 1 -1 -3 -5]
 [ 2  0 -2 -4]]


In [102]:
print(vec_b - vec_a)

[[ 1  3  5  7]
 [ 0  2  4  6]
 [-1  1  3  5]
 [-2  0  2  4]]


In [103]:
print(np.log(vec_a))

[[0.        ]
 [0.69314718]
 [1.09861229]
 [1.38629436]]


In [104]:
print(np.round(np.log(vec_a),2))

[[0.  ]
 [0.69]
 [1.1 ]
 [1.39]]


 ## 1.6 Matrix scalar operations

In [105]:
print(np.sum(vec_a)) # sucet
print(np.mean(vec_a)) # priemer
print(np.var(vec_a)) # rozptil
print(np.std(vec_a)) # smerodajna odchylka
print(np.min(vec_a), np.max(vec_a)) #min, max

10
2.5
1.25
1.118033988749895
1 4


In [106]:
mat

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [107]:
print("Max of mat along axis 0: ", np.max(mat, 0))
print("Max of mat along axis 1: ", np.max(mat, 1))
print("Mean of mat along axis 0: ", np.mean(mat, 0))
print("Mean of mat along axis 1: ", np.mean(mat, 1))

Max of mat along axis 0:  [10 11 12]
Max of mat along axis 1:  [ 3  6  9 12]
Mean of mat along axis 0:  [5.5 6.5 7.5]
Mean of mat along axis 1:  [ 2.  5.  8. 11.]


Determinant

In [108]:
matrix = np.random.rand(4,4)
matrix
# np.linalg.det(matrix)

array([[0.20675984, 0.04931841, 0.78705339, 0.15065834],
       [0.6965454 , 0.06078803, 0.29366639, 0.45368177],
       [0.71476236, 0.94711872, 0.24533868, 0.05306217],
       [0.8653446 , 0.00227389, 0.02802614, 0.9839359 ]])

Get diagonal from matrix

In [109]:
print(np.diag(matrix))

[0.20675984 0.06078803 0.24533868 0.9839359 ]


In [110]:
print(np.diag(matrix,2))

[0.78705339 0.45368177]


In [111]:
print(np.diag(matrix,-1))

[0.6965454  0.94711872 0.02802614]


In [112]:
A

array([[1, 2],
       [3, 4]])

In [113]:
print(np.repeat(A, 2,axis=0))

[[1 2]
 [1 2]
 [3 4]
 [3 4]]


In [114]:
np.repeat(A, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [115]:
print(np.repeat(A, 2,axis=1))

[[1 1 2 2]
 [3 3 4 4]]


In [116]:
A

array([[1, 2],
       [3, 4]])

In [117]:
np.append(A, A*(-1),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [-1, -2],
       [-3, -4]])

In [118]:
np.append(A, A*(-1),axis=1)

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

In [119]:
matrix

array([[0.20675984, 0.04931841, 0.78705339, 0.15065834],
       [0.6965454 , 0.06078803, 0.29366639, 0.45368177],
       [0.71476236, 0.94711872, 0.24533868, 0.05306217],
       [0.8653446 , 0.00227389, 0.02802614, 0.9839359 ]])

Change shape of matrix

In [120]:
matrix.reshape(2,8)

array([[0.20675984, 0.04931841, 0.78705339, 0.15065834, 0.6965454 ,
        0.06078803, 0.29366639, 0.45368177],
       [0.71476236, 0.94711872, 0.24533868, 0.05306217, 0.8653446 ,
        0.00227389, 0.02802614, 0.9839359 ]])

Matrix concatenation

In [121]:
np.concatenate((vec_a, vec_b.T), 0)

array([[1],
       [2],
       [3],
       [4],
       [2],
       [4],
       [6],
       [8]])

In [122]:
np.concatenate((vec_a, vec_b.T), 1)

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [123]:
np.array((vec_a, vec_b))

/var/folders/mt/zbsgqls91d5c1dt725ckq4lc0000gn/T/ipykernel_92509/2904819320.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array((vec_a, vec_b))


array([array([[1],
              [2],
              [3],
              [4]]), array([[2, 4, 6, 8]])], dtype=object)

 ## 1.7 Matrix vector operations

Velmi dolezitymi operaciami s maticami su vypocty skalarnych a vektorovych sucinov. Tieto operacie si je potrebne osvojit a vediet sa orientovat v roznych zapisoch.

In [124]:
mat_a = np.array([[1, 2, 3]])
mat_b = np.array([[4, 5, 6]])

In [125]:
print(mat_a * mat_b)    # elementwise
print(mat_a.T * mat_b)  # vektorovy sucin
print(mat_a * mat_b.T)  # vektorovy sucin
print(mat_a.T @ mat_b)  # skalarny sucin

[[ 4 10 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


# Linear algebra:

In [126]:
V, D = np.linalg.eig(np.random.rand(3, 3))
print("Eigen values: \n",V,"\n Eigen matrix\n",D)

Eigen values: 
 [ 2.0846853   0.27170658 -0.11421065] 
 Eigen matrix
 [[-0.42890988 -0.58683229 -0.01937808]
 [-0.57963736  0.70402568 -0.64474848]
 [-0.69286134 -0.39996962  0.76414913]]


In [127]:
U, S, V = np.linalg.svd(np.random.rand(3, 3))
print("SVD single value decomposition: \n", U,"\n Eigen matrix\n",S,"\n Eigen matrix\n",V) # a = U * S * V'

SVD single value decomposition: 
 [[-0.59606161  0.75147626  0.2828321 ]
 [-0.69874824 -0.31194274 -0.64377218]
 [-0.39555209 -0.58135631  0.7110298 ]] 
 Eigen matrix
 [1.52464432 0.57674534 0.20463057] 
 Eigen matrix
 [[-0.33653211 -0.76980987 -0.54234574]
 [ 0.74925661  0.12996892 -0.64940174]
 [ 0.57040396 -0.62490067  0.53304642]]
